# YDB configuration options and their values
# are described in documentaion https://ydb.tech/en/docs/deploy/configuration/config

# Option will be removed further
use_new_style_kikimr_cfg: true
yaml_config_enabled: true

log:
  cluster_name: "lbk-devslice-1-mirror-3dc" # Change cluster name in order to have better experience with logs searching in Monium.
  sys_log: true
  uaclient_config:
    uri: "[fd53::1]:16400"
    grpc_max_message_size: 4194304

host_configs: # the list of available host configurations in the cluster.
# NOTE: in mirror-3-dc-3-nodes configuration we have to use hosts with more than 3 physical disks.
- drive:
  - path: &disk_path_1 changeme
    type: SSD
  - path: &disk_path_2 changeme
    type: SSD
  - path: &disk_path_3 changeme
    type: SSD
    # Add more disks if required.
  host_config_id: 1
hosts:
- host: &host_1 changeme       # storage node DNS name
  host_config_id: 1                 # numeric host configuration template identifier
  location:                   # this parameter describes where host is located.
    body: 1                         # string representing a host serial number.
    data_center: 'DCA'           # string representing the datacenter / availability zone where the host is located.
                                    # if cluster is deployed using mirror-3-dc fault tolerance mode, all hosts must be distributed
                                    # across 3 datacenters.
    rack: '1'                       # string representing a rack identifier where the host is located.
                                    # if cluster is deployed using block-4-2 erasure, all hosts should be distrubited
                                    # accross at least 8 racks.
- host: &host_2 changeme
  host_config_id: 1
  location:
    body: 2
    data_center: 'DCB'
    rack: '2'
- host: &host_3 changeme
  host_config_id: 1
  location:
    body: 3
    data_center: 'DCC'
    rack: '3'

# static erasure is the parameter that
# describes the fault tolerance mode of the
# cluster. See docs for more details https://ydb.tech/en/docs/deploy/configuration/config#domains-blob
static_erasure: mirror-3-dc
state_storage:
  allow_incorrect: true
  node_ids: [1, 2, 3]
fail_domain_type: disk

# NOTE(shmel1k@): this template domains_config differs from production configuration.
# It will be fixed soon, stay tuned.
domains:
  # There can be only one root domain in a cluster. Domain name prefixes all scheme objects names, e.g. full name of a table table1 in database db1.
  # in a cluster with domains_config.domain.name parameter set to Root would be equal to /Root/db1/table1
  - domain_name: Root
    dynamic_slots: 8
    databases:
      - name: "testdb"
        storage_units:
          - count: 4  # How many groups will be allocated for database
            kind: ssd # What storage will group use
        compute_units:
          - count: 6 # How many dynamic nodes will database have
            kind: slot
            zone: any
    storage_pools:
      - kind: ssd
        num_groups: 1
    storage_pool_kinds:
    - kind: ssd
      # fault tolerance mode name - none, block-4-2, or mirror-3-dc.
      # See docs for more details https://ydb.tech/en/docs/deploy/configuration/config#domains-blob
      erasure: mirror-3-dc
      fail_domain_type: disk
      filter_properties:
        type: SSD # device type to match host_configs.drive.type

table_service_config:
  sql_version: 1

sys:
  executors:
    batch:
      spin_threshold: 50
      threads: 2
      max_threads: 2
      priority: 10
    ic:
      spin_threshold: 50
      threads: 3
      max_threads: 7
      priority: 40
      max_avg_ping_deviation: 500
    io:
      threads: 2
      max_threads: 1
    system:
      spin_threshold: 50
      threads: 5
      max_threads: 13
      priority: 30
    user:
      spin_threshold: 50
      threads: 10
      max_threads: 1
      priority: 20
  scheduler:
    resolution: 64

blob_storage_config:         # configuration of static blobstorage group.
                             # YDB uses this group to store system tablets' data, like SchemeShard
  service_set:
    groups:
    - erasure_species: mirror-3-dc # fault tolerance mode name for the static group
      rings:          # in mirror-3-dc must have exactly 3 rings or availability zones
      - fail_domains:  # first record: fail domains of the static group describe where each vdisk of the static group should be located.
        - vdisk_locations:
          - node_id: 1
            pdisk_category: &pdisk_category 1 # 1 - SSD, 0 - HDD
            path: *disk_path_1
            pdisk_guid: 1
        - vdisk_locations:
          - node_id: 1
            pdisk_category: *pdisk_category
            path: *disk_path_2
            pdisk_guid: 2
        - vdisk_locations:
          - node_id: 1
            pdisk_category: *pdisk_category
            path: *disk_path_3
            pdisk_guid: 3
      - fail_domains: # second ring: fail domains of the static group describe where each vdisk of the static group should be located.
        - vdisk_locations:
          - node_id: 2
            pdisk_category: *pdisk_category
            path: *disk_path_1
            pdisk_guid: 4
        - vdisk_locations:
          - node_id: 2
            pdisk_category: *pdisk_category
            path: *disk_path_2
            pdisk_guid: 5
        - vdisk_locations:
          - node_id: 2
            pdisk_category: *pdisk_category
            path: *disk_path_3
            pdisk_guid: 6
      - fail_domains: # third ring: fail domains of the static group describe where each vdisk of the static group should be located.
        - vdisk_locations:
          - node_id: 3
            pdisk_category: *pdisk_category
            path: *disk_path_1
            pdisk_guid: 7
        - vdisk_locations:
          - node_id: 3
            pdisk_category: *pdisk_category
            path: *disk_path_2
            pdisk_guid: 8
        - vdisk_locations:
          - node_id: 3
            pdisk_category: *pdisk_category
            path: *disk_path_3
            pdisk_guid: 9

# TODO: migrate to channel_profile_config
# profiles:
#   - channels:
#     - storage_pool_kind: ssd
#     - storage_pool_kind: ssd
#     - storage_pool_kind: ssd

interconnect_config:
    start_tcp: true
grpc_config:

kafka_proxy_config:
  enable_kafka_proxy: true
  listening_port: 9092

channel_profile_config:
  profile:
  - channel:
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    profile_id: 0